---

# In your Travis Settings...
#
# Set PUBLISH_IMAGES to 'yes' to enable publishing to Docker Hub.
# You will also need to provide values for  DOCKER_USERNAME and DOCKER_PASSWORD.
# Set TRIGGER_AWX to 'yes' to enable AWX job triggering.
# Enabling TRIGGER_AWX is only effective if PUBLISH_IMAGES is also set.
#
# If you set TRIGGER_AWX you must also set the following: -
#
# - AWX_HOST (the fully-qualified URL to AWX)
# - AWX_JOB_NAME The name of the Job to run.
#                Avoid encrypting this one but make sure you use double-quotes
#                as you'll need to escape characters like whitespace
# - AWX_USER (The username of someone that can run the Job)
# - AWX_USER_PASSWORD (The user's password)

os: linux
language: python
python:
- '3.8'
services:
- docker

stages:
- name: test
- name: trigger awx
  if: |
    branch = im-travis \
    AND env(PUBLISH_IMAGES) = yes \
    AND env(TRIGGER_AWX) = yes
- name: publish tag
  if: |
    tag IS present \
    AND env(PUBLISH_IMAGES) = yes
- name: publish stable
  if: |
    tag IS present \
    AND tag =~ ^([0-9]+\.){1,2}[0-9]+$ \
    AND env(PUBLISH_IMAGES) = yes

before_install:
# The user can define the following variables in their Travis Settings.
# If they're not defined then apply sensible defaults.
- export BE_NAMESPACE=${BE_NAMESPACE-xchem}
- export STACK_NAMESPACE=${STACK_NAMESPACE:-xchem}
- echo ${PUBLISH_IMAGES}
- echo ${TRIGGER_AWX}

install:
- pip install -r awx/requirements.txt

before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

jobs:
  include:

  # Test-stage jobs...

  - stage: test
    name: Container Test
    script:
    - docker build -t ${STACK_NAMESPACE}/fragalysis-stack:latest .
    - docker-compose -f docker-compose.test.yml up --build --exit-code-from tests --abort-on-container-exit
    - if [ ${PUBLISH_IMAGES} == "yes" ]; then
      docker push ${STACK_NAMESPACE}/fragalysis-stack:latest;
      fi

  # Publish-stage jobs...
  # Every successful master build results in a latest image
  # and every tag results in a tagged image in Docker Hub.
  # Tags that match a RegEx are considered 'official' tags
  # and also result in a 'stable' image tag.

  - stage: publish tag
    name: Tagged Container
    script:
    - docker build -t ${STACK_NAMESPACE}/fragalysis-stack:${TRAVIS_TAG} .
    - docker push ${STACK_NAMESPACE}/fragalysis-stack:${TRAVIS_TAG}

  - stage: publish stable
    name: Stable Container
    script:
    - docker pull ${STACK_NAMESPACE}/fragalysis-stack:${TRAVIS_TAG}
    - docker tag ${STACK_NAMESPACE}/fragalysis-stack:${TRAVIS_TAG} ${STACK_NAMESPACE}/fragalysis-stack:stable
    - docker push ${STACK_NAMESPACE}/fragalysis-stack:stable

  - stage: trigger awx
    name: Trigger AWX
    script:
    - ./awx/trigger.sh
