version: '3'

services:
  mysql:
    image: mysql:5.7.23
    volumes:
       - ../django_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_db
      MYSQL_PASSWORD: django_password
      MYSQL_USER: django
  tests:
    image: xchem/fragalysis-stack
    command: ["/code/wait-for-it.sh", "db:5432", "--", "/bin/bash", "/code/test_entry.sh"]
    volumes:
      - ../logs:/code/logs/
      - ../media:/code/media/
    ports:
      - "80:80"
    depends_on:
      - mysql
