version: '3'

services:
  db:
    image: postgres
    volumes:
       - ../django_data:/var/lib/postgresql/data
  web:
    image: xchem/fragalysis-stack:latest
    command: /bin/bash /code/launch-stack.sh
    volumes:
      - ../logs:/code/logs/
      - ../media:/code/media/
    ports:
      - "80:80"
    depends_on:
      - db
