version: '3'

services:
  mysql:
    image: mysql:5.7.23
    volumes:
       - ../django_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_db
      MYSQL_PASSWORD: django_password
      MYSQL_USER: django
  web:
    container_name: web_dock
    image: xchem/fragalysis-stack:latest
    command: /bin/bash /code/launch-stack.sh
    volumes:
      - ../logs:/code/logs/
      - ../media:/code/media/
    ports:
      - "80:80"
    depends_on:
      - db
